### ISSUE TITLE
 replaceWithOsm.py

### ISSUE THREAD

**Issue by dr-eamy** [tibnor/kartverket2osm#11]
Hei, jeg forsøker og kjøre  replaceWithOsm.py på  1032_water_part_0_58.00_58.35_6.85_7.10.osm, men får følgende feil.

$ python replaceWithOsm.py 1032_water_part_0_58.00_58.35_6.85_7.10.osm output_part0.osm --import:water
  File "replaceWithOsm.py", line 231
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by tibnor** [comment]
Hei @dr-eamy, hvilken versjon av python kjører du? replaceWithOs.py er lagd for python 2.7.

**Comment by dr-eamy** [comment]
hei @tibnor det løste seg når jeg bare fant en maskin med 2.7.10 :)  
forsøkte via python 3.5 som er instalert under cygwin, og her virket det ikke! :p
