### ISSUE TITLE
Tagger blir overskrevet, hvis ny vei inneholder samme tag

### ISSUE THREAD

**Issue by anderfo** [tibnor/kartverket2osm#2]
På arealimporten dukker det av og til opp skog på mange små øyer som av en eller annen grunn mangler i kystlinje-importen. Scriptet bør kunne gi disse øyene kystlinje, for det tar tid å søke dem opp manuelt.

**Comment by tibnor** [comment]
Problemet er at replaceWithOsm overskriver natural=coastline taggen når en tilsvarende vei med natural=wood blir importert.

**Comment by anderfo** [comment]
Ja, det høres riktig ut (dvs., riktig at det er en feil ;) ).
Dersom alle disse natural=wood lages som multipolygoner vil det kanskje gå bedre? Det er ihvertfall slik jeg har løst det på øyer med skog.
