### ISSUE TITLE
Feilmelding mangler referanse til vegene som er årsak til feilen hvis veien ikke inneholder noder

### ISSUE THREAD

**Issue by anderfo** [tibnor/kartverket2osm#5]
Jeg har flere ganger opplevd feilmeldingen "ValueError: Two ways have same hash:" for duplikatveger, men denne er vanskelig å feilsøke ettersom utskriften av waynr/nodenr ikke fungerer. Dermed må man lete manuelt i JOSM, og det er vanskelig i endel tilfeller (JOSM validator finner ikke alltid duplikatene).

Fullstendig feilmelding kan se slik ut:

Traceback (most recent call last):
  File "/Users/anderfo/bin/kartverket2osm/replaceWithOsm.py", line 314, in <module>
    replaceWithOsm(fileName, fileNameOut,importAreal,importWater,importWay)
  File "/Users/anderfo/bin/kartverket2osm/replaceWithOsm.py", line 117, in replaceWithOsm
    (nodes,nodesHashed,ways,waysHashed,relationsHashed) = hashOsm(osmImport)
  File "/Users/anderfo/bin/kartverket2osm/replaceWithOsm.py", line 76, in hashOsm
    raise ValueError("Two ways have same hash: %s" % ref)
ValueError: Two ways have same hash:

**Comment by tibnor** [comment]
Denne feilen oppstår hvis veien ikke inneholder noder. Slik som kan skje ved en osm fil med action="delete".
