### ISSUE TITLE
Feil retning på bekker som tangerer vann eller riverbank

### ISSUE THREAD

**Issue by anderfo** [tibnor/kartverket2osm#6]
Endel bekker/elver som f.eks. munner ut i samme vann eller riverbank, er koblet sammen. Dermed får halvparten av bekken/elva feil retning.

Bekker/elver som er "innom" vann/riverbank bør automatisk splittes der, før retning beregnes.

**Comment by tibnor** [comment]
Fixed in fdb85cf
