### ISSUE TITLE
Områder med ekstremt mange noder

### ISSUE THREAD

**Issue by anderfo** [tibnor/kartverket2osm#7]
Endel områder, f.eks. lengst sør i Midtre Gauldal, har ekstremt mange noder (unødvendig høy oppløsning). Hvis jeg skal bruke Simplify i JOSM på dette må jeg først laste opp vann, deretter areal og så tilslutt kjøre Simplify...for hvis jeg istedet kjører Simplify allerede ved vannimport, går alt "skeis" ved arealimport.

Derfor lurer jeg på om du kunne kjørt en eller annen form for simplification/forenkling allerede i kartverket2osm?

Det ville redusert datamengdene og opplastingstida (det tar lang tid å laste opp selv små områder med så høy oppløsning) og redusert mengden manuelt arbeid i JOSM.

**Comment by tibnor** [comment]
Dette er implementert i 516582abd7f61b24b52ebb53fda65e4aa29bbab8
